load('../data/nist36_train.mat', 'train_data', 'train_labels')
load('../data/nist36_test.mat', 'test_data', 'test_labels')
load('../data/nist36_valid.mat', 'valid_data', 'valid_labels')
train_data = reshape ( train_data' , 32 , 32 , 1 , [] );
valid_data = reshape ( valid_data' , 32 , 32 , 1 , [] );
test_data  = reshape ( test_data'  , 32 , 32 , 1 , [] );

layers = define_autoencoder();

options = trainingOptions('sgdm',...
                          'InitialLearnRate',1e-2,...
                          'MaxEpochs',20,...
                          'MiniBatchSize',20,...
                          'Shuffle','every-epoch',...
                          'Plot','training-progress',...
                          'VerboseFrequency',20);

[ net tr ]  = trainNetwork(train_data , train_data , layers , options )
